# name: check2
# run-name: ${{ github.head_ref || github.ref_name }}-${{ github.run_number }} 
# on:
#   pull_request:
#     types:
#       [opened, synchronize, reopened]
# jobs: 
#   check2:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Generate token
#         id: generate_token
#         uses: tibdex/github-app-token@v1.8.0
#         with:
#           app_id: ${{ secrets.CLEVERTAP_PLATFORM_BOT_ID }}
#           private_key: ${{ secrets.CLEVERTAP_PLATFORM_BOT_PRIVATE_ACCESS_KEY }}
#       - name: Create Check2 status
#         run: |
#           curl -L \
#           -X POST \
#           -H "Accept: application/vnd.github+json" \
#           -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
#           -H "X-GitHub-Api-Version: 2022-11-28" \
#           https://api.github.com/repos/Yashprime1/genzinfra-cloudformation/check-runs \
#           -d "{\"name\":\"check2\",\"head_sha\":\"${{ github.sha }}\",\"status\":\"in_progress\"}"